version: 0.2

phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 600627330740.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - docker build -t bps-repo .
      - docker tag bps-repo:latest 600627330740.dkr.ecr.us-east-1.amazonaws.com/bps-repo:latest
  post_build:
    commands:
      - docker push 600627330740.dkr.ecr.us-east-1.amazonaws.com/bps-repo:latest
      - echo Writing image definitions file...
      - printf '[{"name":"bps-repo","imageUri":"%s"}]' 600627330740.dkr.ecr.eu-north-1.amazonaws.com/bank-prediction-system:latest > imagedefinitions.json
artifacts:
  files: 
  - imagedefinitions.json